### PR TITLE
Editor: Support changing text direction (LTR/RTL)

### PR DESCRIPTION
**Pull request by mhaggag**
I've added two buttons to the editor toolbar to change text direction to Left-to-right and right-to-left. This is essential for right-to-left language users (e.g. Arabic and Hebrew).

I've used the standard theme icons: format-text-direction-rtl and ltr. I've also listed everpad- variants of the icons even though I haven't added them, to enable overriding the standard ones (which appear to be icons with the text "Left to right" and "Right to left").

### CODE REVIEW

**Comment by nvbn** [comment]
Maybe it need to be in context menu? Tollbar already is overloaded, is better not adding additional items.

**Comment by mhaggag** [comment]
It can be a context menu item, but it's not typical usage. Editors usually display one or two icons to switch directionality in the toolbar (e.g. GMail displays one to reverse the current directionality, Word and LibreOffice Writer display two).

I don't think it'd be easily discoverable in the context menu, since people aren't expecting it there.

Editors usually don't display text direction icons unless they detect a RTL locale or you explicitly enable support for RTL layout in application settings. Perhaps we can do something similar?

Also, text direction can usually be switched using Left/Right Ctrl+Shift (for LTR/RTL respectively). If that's supported, I wouldn't need icons at all--but that's not discoverable at all, and I'm not sure if regular users are aware of it.

**Comment by nvbn** [comment]
Hm, maybe display it only for locales with RTL? If you can do that, i merge it =)

**Comment by mhaggag** [comment]
Hello. Do you require any further changes for this pull request?

**Comment by nvbn** [comment]
No, it's currently good. Thank you =)

**Pull request merged**
