### PR TITLE
Remove progress bar from Everpad Launcher when syncing

### PR DESCRIPTION
**Pull request by cas--**
Most of the time the sync is over too quickly for this progress bar to be of any use and recently I have found it being very distracting because the launcher icon is flickering every 10mins (upon sync) when I have a note open.

### CODE REVIEW

**Comment by nvbn** [comment]
Maybe everpad need settings option for this. My sync delay is one hour, and when i loaded some pictures from phone to evernote, syncing going doesn't fast.

**Comment by hdave** [comment]
I vote that we don't remove this by default.  Currently my sync takes 1-2 minutes and I rely on that to understand what is happening. A setting would be fine of course.

**Comment by cas--** [comment]
That is fair enough, leaving it in makes sense now. :)

I will delve in to the code again at some point and create an option instead.

**Comment by hdave** [comment]
Awesome....thank you.

**Comment by cas--** [comment]
Oh so that's what happens when you push a rebased pull-request branch, sorry for extra noise.

Anyway this branch now has an option 'launcher-progress' added to settings that will allow the launcher progress bar to be disabled.

**Pull request merged**
