### PR TITLE
Use common icons from system themes.

### PR DESCRIPTION
**Pull request by fmoo**
Not sure why we bundle everpad-\* versions of many of the icons when they should
pretty much be installed on the system already using format-\* or various
other prefixes.

### CODE REVIEW

**Comment by fmoo** [comment]
I was sort of curious why these icons are bundled with everpad;  I don't mind closing this out if there was a good reason.

**Comment by nvbn** [comment]
Because in fresh installed system this icons doesn't exist.
And part of it exists only in oxygen/gnome/hicolor.

**Comment by fmoo** [comment]
Hm.  I found most, if not all of them in oxygen and gnome.

But, as you mentioned, hicolor looks to be mostly incomplete.

However, when I switch my theme to hicolor using gnome-tweak-tool, the icons continue to load with this change.  It seems the icon loader is falling back to the /gnome theme's icons when an icon is not present in /hicolor.

Or, maybe it explains it if you are using some other wm that isn't gnome maybe?

**Comment by fmoo** [comment]
Ah, I see;  I just read http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup ;  /hicolor is the _ultimate_ fallback theme.

Also, as you pointed out, oxygen doesn't provide _24px_ icons for these names.

**Comment by fmoo** [comment]
oh hm, but it provides 22px icons and the icon lookup algorithm should consider those.  Oh well, nbd if you don't want this.

**Pull request closed without merging**
